/**
 * AIntern - Final Training Report DOCX Generator (Phase B, Case 2)
 *
 * Chapter-aware editable Word export — same chapter model as
 * finalReportPdf.js, same reused entries/evaluations/verification-appendix
 * builders as logbookDocx.js. Edits made in Word never modify the official
 * record (spec §34); verification is computed server-side and is
 * completely unaffected by narrative chapter content.
 *
 * @file src/services/docx/finalReportDocx.js
 * @created July 12, 2026 - Phase B
 */

import { Document, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel } from 'docx';
import { LAYOUT_DEFAULTS } from '../render/reportLayout';
import { kvTable, entriesSectionChildren, evaluationsSectionChildren, verificationAppendixChildren } from './reportSections';

const rgbHex = ([r, g, b]) =>
  [r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('').toUpperCase();

/**
 * Generate and download the .docx.
 * @param {Object} p - { profile, internship, reportTitle, chapters, draft,
 *   snapshots, evaluations, template, layout, verification, qrPng }
 */
export async function generateFinalReportDocx({
  profile, internship, reportTitle, chapters = [], draft = {},
  snapshots = [], evaluations = [], template = null,
  layout = null, verification = null, qrPng = null,
}) {
  const L = { ...LAYOUT_DEFAULTS, ...(layout ?? {}) };
  const title = reportTitle || 'Final Training Report';
  const accent = rgbHex(L.accent);
  const children = [];

  // ── Cover ──
  children.push(
    new Paragraph({
      children: [new TextRun({ text: title, bold: true, size: 52, color: accent })],
      spacing: { before: 1200, after: 200 },
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({ text: profile?.full_name || 'Intern', size: 32 })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: 'Generated by AIntern — logbook evidence supervisor-approved and digitally signed',
        size: 16, color: '64748B',
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    kvTable([
      ['Intern', profile?.full_name || '-'],
      ['University / Institution', profile?.university || '-'],
      ['Course / Programme', profile?.course || '-'],
      ['Host company', internship?.company_name || '-'],
      ['Department', internship?.department || '-'],
      ['Supervisor', internship?.supervisor_name || '-'],
      ['Internship period', `${internship?.start_date} to ${internship?.end_date}`],
      ['Report chapters', String(chapters.length)],
    ]),
  );

  // ── Chapters ──
  chapters.forEach((ch) => {
    if (ch.kind === 'auto_entries') {
      children.push(...entriesSectionChildren({ snapshots, template, layout: L, accent }));
      return;
    }
    if (ch.kind === 'auto_evaluations') {
      children.push(...evaluationsSectionChildren({ evaluations, layout: L, accent }));
      return;
    }

    const text = String(draft?.[ch.chapter_id] ?? '').trim();
    children.push(new Paragraph({
      children: [new TextRun({ text: ch.chapter_title, bold: true, size: 30, color: accent })],
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
    }));
    const paragraphs = (text || '(Not yet written.)').split(/\n+/);
    paragraphs.forEach((para) => {
      children.push(new Paragraph({
        children: [new TextRun({
          text: para,
          size: 20,
          italics: !text,
          color: text ? '334155' : '94A3B8',
        })],
        spacing: { after: 160 },
      }));
    });
  });

  // ── Verification Appendix ──
  children.push(...verificationAppendixChildren({ verification, qrPng, accent }));

  const doc = new Document({
    creator: 'AIntern',
    title,
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(doc);
  const name = (profile?.full_name || 'intern').replace(/\s+/g, '_');
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `AIntern_FinalReport_${name}_${internship?.start_date}_${internship?.end_date}.docx`;
  a.click();
  URL.revokeObjectURL(a.href);
}

export default generateFinalReportDocx;
