/**
 * AIntern - Logbook DOCX Generator (v1.1 R3, spec §22)
 *
 * Editable Microsoft Word export generated client-side from a FROZEN
 * report snapshot — same model and layout as the HTML preview and PDF.
 * Edits made in Word never modify the official record (spec §34).
 *
 * @file src/services/docx/logbookDocx.js
 * @created July 11, 2026 - v1.1 R3
 * @updated July 12, 2026 - Phase B: entries/evaluations/verification-appendix
 *   building extracted to reportSections.js (shared with finalReportDocx.js) —
 *   behavior unchanged, just no longer duplicated.
 */

import {
  Document, Packer, Paragraph, TextRun, AlignmentType,
} from 'docx';
import { LAYOUT_DEFAULTS } from '../render/reportLayout';
import { kvTable, entriesSectionChildren, evaluationsSectionChildren, verificationAppendixChildren } from './reportSections';

const rgbHex = ([r, g, b]) =>
  [r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('').toUpperCase();

/**
 * Generate and download the .docx.
 * @param {Object} p - { profile, internship, snapshots, evaluations, template, layout, verification, qrPng }
 */
export async function generateLogbookDocx({
  profile, internship, snapshots, evaluations, template,
  layout = null, verification = null, qrPng = null,
}) {
  const L = { ...LAYOUT_DEFAULTS, ...(layout ?? {}) };
  const accent = rgbHex(L.accent);
  const evals = L.show_evaluations ? evaluations : [];
  const children = [];

  // ── Cover ──
  children.push(
    new Paragraph({
      children: [new TextRun({ text: L.title, bold: true, size: 56, color: accent })],
      spacing: { before: 1200, after: 200 },
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({ text: profile?.full_name || 'Intern', size: 32 })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: 'Generated by AIntern — every entry supervisor-approved and digitally signed',
        size: 16, color: '64748B',
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    kvTable([
      ['Intern', profile?.full_name || '-'],
      ['University / Institution', profile?.university || '-'],
      ['Course / Programme', profile?.course || '-'],
      ['Host company', internship?.company_name || '-'],
      ['Department', internship?.department || '-'],
      ['Supervisor', internship?.supervisor_name || '-'],
      ['Internship period', `${internship?.start_date} to ${internship?.end_date}`],
      ['Approved daily entries', String(snapshots.length)],
      ['Supervisor evaluations', String(evaluations.length)],
    ]),
  );

  // ── Entries ──
  children.push(...entriesSectionChildren({ snapshots, template, layout: L, accent }));

  // ── Evaluations ──
  if (evals.length > 0) {
    children.push(...evaluationsSectionChildren({ evaluations: evals, layout: L, accent }));
  }

  // ── Verification Appendix ──
  children.push(...verificationAppendixChildren({ verification, qrPng, accent }));

  const doc = new Document({
    creator: 'AIntern',
    title: L.title,
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(doc);
  const name = (profile?.full_name || 'intern').replace(/\s+/g, '_');
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `AIntern_Logbook_${name}_${internship?.start_date}_${internship?.end_date}.docx`;
  a.click();
  URL.revokeObjectURL(a.href);
}

export default generateLogbookDocx;
