/**
 * AIntern - Logbook DOCX Generator (v1.1 R3, spec §22)
 *
 * Editable Microsoft Word export generated client-side from a FROZEN
 * report snapshot — same model and layout as the HTML preview and PDF.
 * Edits made in Word never modify the official record (spec §34).
 *
 * @file src/services/docx/logbookDocx.js
 * @created July 11, 2026 - v1.1 R3
 */

import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, WidthType, ImageRun, AlignmentType, BorderStyle,
} from 'docx';
import { LAYOUT_DEFAULTS } from '../render/reportLayout';
import { fieldRows as buildFieldRows } from '../render/fieldRows';

const rgbHex = ([r, g, b]) =>
  [r, g, b].map((v) => v.toString(16).padStart(2, '0')).join('').toUpperCase();

function b64ToUint8(dataUrl) {
  const b64 = String(dataUrl).split(',')[1] ?? '';
  const bin = atob(b64);
  const arr = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) arr[i] = bin.charCodeAt(i);
  return arr;
}

// List-type fields keep their lines as an array here (rather than joining
// to a string) so kvTable() below can render each as its own paragraph —
// Word bullets read better as separate paragraphs than \n-joined text.
function fieldRows(data, template) {
  return buildFieldRows(data, template).map(({ field_name, lines }) => [
    field_name,
    lines.length > 1 ? lines : lines[0],
  ]);
}

const cellBorders = {
  top: { style: BorderStyle.SINGLE, size: 2, color: 'E2E8F0' },
  bottom: { style: BorderStyle.SINGLE, size: 2, color: 'E2E8F0' },
  left: { style: BorderStyle.SINGLE, size: 2, color: 'E2E8F0' },
  right: { style: BorderStyle.SINGLE, size: 2, color: 'E2E8F0' },
};

function kvTable(rows, boldColWidth = 32) {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: rows.map(([k, v]) => new TableRow({
      children: [
        new TableCell({
          borders: cellBorders,
          width: { size: boldColWidth, type: WidthType.PERCENTAGE },
          shading: { fill: 'F8FAFC' },
          children: [new Paragraph({ children: [new TextRun({ text: String(k), bold: true, size: 18 })] })],
        }),
        new TableCell({
          borders: cellBorders,
          // Array value (list-type field, e.g. bulleted daily activities):
          // one paragraph per bullet. Everything else: unchanged single line.
          children: Array.isArray(v)
            ? v.map((line) => new Paragraph({ children: [new TextRun({ text: `• ${line}`, size: 18 })] }))
            : [new Paragraph({ children: [new TextRun({ text: String(v), size: 18 })] })],
        }),
      ],
    })),
  });
}

const RUBRIC_LABELS = {
  communication: 'Communication',
  punctuality: 'Punctuality & discipline',
  problem_solving: 'Problem-solving',
  quality: 'Quality of work',
  initiative: 'Initiative',
  teamwork: 'Teamwork',
  professionalism: 'Professionalism',
};

/**
 * Generate and download the .docx.
 * @param {Object} p - { profile, internship, snapshots, evaluations, template, layout, verification, qrPng }
 */
export async function generateLogbookDocx({
  profile, internship, snapshots, evaluations, template,
  layout = null, verification = null, qrPng = null,
}) {
  const L = { ...LAYOUT_DEFAULTS, ...(layout ?? {}) };
  const accent = rgbHex(L.accent);
  const evals = L.show_evaluations ? evaluations : [];
  const children = [];

  // ── Cover ──
  children.push(
    new Paragraph({
      children: [new TextRun({ text: L.title, bold: true, size: 56, color: accent })],
      spacing: { before: 1200, after: 200 },
      alignment: AlignmentType.CENTER,
    }),
    new Paragraph({
      children: [new TextRun({ text: profile?.full_name || 'Intern', size: 32 })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 100 },
    }),
    new Paragraph({
      children: [new TextRun({
        text: 'Generated by AIntern — every entry supervisor-approved and digitally signed',
        size: 16, color: '64748B',
      })],
      alignment: AlignmentType.CENTER,
      spacing: { after: 400 },
    }),
    kvTable([
      ['Intern', profile?.full_name || '-'],
      ['University / Institution', profile?.university || '-'],
      ['Course / Programme', profile?.course || '-'],
      ['Host company', internship?.company_name || '-'],
      ['Department', internship?.department || '-'],
      ['Supervisor', internship?.supervisor_name || '-'],
      ['Internship period', `${internship?.start_date} to ${internship?.end_date}`],
      ['Approved daily entries', String(snapshots.length)],
      ['Supervisor evaluations', String(evaluations.length)],
    ]),
  );

  // ── Entries ──
  children.push(new Paragraph({
    children: [new TextRun({ text: 'Approved Daily Entries', bold: true, size: 32, color: accent })],
    heading: HeadingLevel.HEADING_1,
    pageBreakBefore: true,
    spacing: { after: 200 },
  }));

  snapshots.forEach((snap) => {
    children.push(new Paragraph({
      children: [
        new TextRun({ text: snap.entry_date, bold: true, size: 24, color: accent }),
        new TextRun({ text: `   (approved ${String(snap.approved_at).slice(0, 10)})`, size: 16, color: '64748B' }),
      ],
      spacing: { before: 300, after: 100 },
    }));
    const rows = fieldRows(snap.content, template);
    if (rows.length > 0) children.push(kvTable(rows));
    if (L.show_comments && snap.supervisor_comment) {
      children.push(new Paragraph({
        children: [new TextRun({ text: `Supervisor: ${snap.supervisor_comment}`, italics: true, size: 18, color: '475569' })],
        spacing: { before: 100 },
      }));
    }
    if (L.show_signatures && String(snap.supervisor_signature ?? '').startsWith('data:image')) {
      try {
        children.push(new Paragraph({
          children: [new ImageRun({ data: b64ToUint8(snap.supervisor_signature), transformation: { width: 140, height: 47 } })],
          spacing: { before: 80 },
        }));
        children.push(new Paragraph({
          children: [new TextRun({ text: `Signed by ${snap.supervisor_name}`, size: 14, color: '94A3B8' })],
        }));
      } catch { /* signature optional */ }
    }
  });

  // ── Evaluations ──
  if (evals.length > 0) {
    children.push(new Paragraph({
      children: [new TextRun({ text: 'Supervisor Evaluations', bold: true, size: 32, color: accent })],
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
    }));
    evals.forEach((ev) => {
      children.push(new Paragraph({
        children: [new TextRun({ text: `${ev.period_start} to ${ev.period_end} (${ev.cadence_days}-day review)`, bold: true, size: 22 })],
        spacing: { before: 300, after: 100 },
      }));
      const scoreRows = Object.entries(RUBRIC_LABELS)
        .filter(([k]) => ev.scores?.[k])
        .map(([k, label]) => [label, `${ev.scores[k]} / 5`]);
      (ev.custom_kpis ?? []).forEach((kpi) => {
        if (kpi?.name && kpi?.score) scoreRows.push([`${kpi.name} (custom)`, `${kpi.score} / 5`]);
      });
      if (scoreRows.length > 0) children.push(kvTable(scoreRows, 60));
      [['Strengths', ev.comments?.strengths], ['Areas for improvement', ev.comments?.improvements]]
        .filter(([, v]) => v && String(v).trim())
        .forEach(([label, text]) => {
          children.push(new Paragraph({
            children: [
              new TextRun({ text: `${label}: `, bold: true, size: 18 }),
              new TextRun({ text: String(text), size: 18 }),
            ],
            spacing: { before: 100 },
          }));
        });
      if (L.show_signatures && String(ev.supervisor_signature ?? '').startsWith('data:image')) {
        try {
          children.push(new Paragraph({
            children: [new ImageRun({ data: b64ToUint8(ev.supervisor_signature), transformation: { width: 140, height: 47 } })],
            spacing: { before: 80 },
          }));
        } catch { /* optional */ }
      }
    });
  }

  // ── Verification Appendix ──
  if (verification?.verification_id) {
    children.push(new Paragraph({
      children: [new TextRun({ text: 'Verification Appendix', bold: true, size: 32, color: accent })],
      heading: HeadingLevel.HEADING_1,
      pageBreakBefore: true,
      spacing: { after: 200 },
    }));
    children.push(kvTable([
      ['Verification status', 'VERIFIED'],
      ['Verification ID', verification.verification_id],
      ['Report version', `v${verification.version}`],
      ['Snapshot created', String(verification.created_at).slice(0, 10)],
      ['Record fingerprint', String(verification.content_hash)],
      ['Verify online', verification.verify_url],
    ], 32));
    if (qrPng) {
      try {
        children.push(new Paragraph({
          children: [new ImageRun({ data: b64ToUint8(qrPng), transformation: { width: 120, height: 120 } })],
          spacing: { before: 200 },
        }));
      } catch { /* optional */ }
    }
    children.push(new Paragraph({
      children: [new TextRun({
        text: 'Scan the QR code or visit the link above to confirm this document was generated '
          + 'from an officially verified internship record. Edits made to this Word document do '
          + 'not modify the official record maintained by AIntern.',
        size: 16, color: '475569',
      })],
      spacing: { before: 150 },
    }));
  }

  const doc = new Document({
    creator: 'AIntern',
    title: L.title,
    sections: [{ children }],
  });

  const blob = await Packer.toBlob(doc);
  const name = (profile?.full_name || 'intern').replace(/\s+/g, '_');
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = `AIntern_Logbook_${name}_${internship?.start_date}_${internship?.end_date}.docx`;
  a.click();
  URL.revokeObjectURL(a.href);
}

export default generateLogbookDocx;
