/**
 * AIntern - Template Studio Service (Phase 3, Session 11)
 *
 * "Logbook and forms generated by AI from image or PDF uploaded by user."
 * Sends the file to ai-gateway `import_form` (BYOK/bundled, metered,
 * server-side sanitized), then saves the approved draft as the intern's
 * own template and assigns it to the internship (daily_template_id).
 *
 * @file src/services/api/templateStudioService.js
 * @created July 10, 2026 - Session 11
 */

import { supabase } from '../supabase/client';
import { internDb } from '../offline/internDb';

const MAX_BYTES = 5 * 1024 * 1024;

function fileToBase64(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      const [, b64] = String(reader.result).split(',');
      resolve(b64);
    };
    reader.onerror = () => reject(new Error('Could not read the file'));
    reader.readAsDataURL(file);
  });
}

class TemplateStudioService {
  /** Upload a form photo/PDF → sanitized template draft (not yet saved). */
  async extractTemplate(file, provider = 'gemini') {
    if (!file) return { success: false, error: 'Choose a file first.' };
    if (file.size > MAX_BYTES) {
      return { success: false, error: 'File too large — keep it under 5 MB.' };
    }
    try {
      const file_base64 = await fileToBase64(file);
      const { data, error } = await supabase.functions.invoke('ai-gateway', {
        body: { action: 'import_form', mime: file.type, file_base64, provider },
      });
      if (error) {
        let message = error.message;
        try {
          const ctx = await error.context?.json?.();
          if (ctx?.error) message = ctx.error;
        } catch { /* keep original */ }
        return { success: false, error: message };
      }
      return data;
    } catch (err) {
      return { success: false, error: err.message };
    }
  }

  /**
   * Save the approved draft as the intern's own template and assign it
   * to the internship. Owner RLS scopes everything.
   */
  async saveAndApply(internship, draft) {
    try {
      const { data: { user } } = await supabase.auth.getUser();
      if (!user) return { success: false, error: 'Not logged in' };

      const templateId = `custom-${user.id.slice(0, 8)}-${Date.now()}`;
      const { data: tpl, error: tplErr } = await supabase
        .from('templates')
        .insert({
          template_id: templateId,
          template_name: draft.template_name,
          description: 'Imported from an uploaded form via AI Template Studio',
          fields_schema: draft.fields_schema,
          is_public: false,
          owner_id: user.id,
        })
        .select()
        .single();
      if (tplErr) return { success: false, error: tplErr.message };

      const { error: itnErr } = await supabase
        .from('internships')
        .update({ daily_template_id: tpl.id })
        .eq('id', internship.id);
      if (itnErr) return { success: false, error: itnErr.message };

      // Cache for offline rendering
      await internDb.templateCache.put({
        template_id: tpl.template_id,
        template: tpl,
        cached_at: new Date().toISOString(),
      });

      return { success: true, template: tpl };
    } catch (err) {
      return { success: false, error: err.message };
    }
  }

  /** Revert the internship to the default AIntern daily template. */
  async revertToDefault(internship) {
    const { error } = await supabase
      .from('internships')
      .update({ daily_template_id: null })
      .eq('id', internship.id);
    if (error) return { success: false, error: error.message };
    return { success: true };
  }
}

export const templateStudioService = new TemplateStudioService();
export default templateStudioService;
