/**
 * AIntern - Final Training Report PDF Generator (Phase B, Case 2)
 *
 * Chapter-aware export: walks a frozen chapter list (from
 * report_versions.content.chapters) and renders each one —
 *   'narrative'         -> the student's own written prose (or a
 *                           "not yet written" placeholder)
 *   'auto_entries'      -> the SAME approved-entries table the logbook uses
 *   'auto_evaluations'  -> the SAME evaluations rubric the logbook uses
 * — then appends the identical, unmodified Verification Appendix + QR
 * (spec §25-27) that the logbook PDF already ships. Narrative content is
 * presentation only; verification is computed server-side in
 * create_report_snapshot() from approved entries/evaluations alone, same
 * as every other report type.
 *
 * @file src/services/pdf/finalReportPdf.js
 * @created July 12, 2026 - Phase B
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { LAYOUT_DEFAULTS } from '../render/reportLayout';
import { drawEntriesSection, drawEvaluationsSection, drawVerificationAppendix, ensureSpace } from './reportSections';

const M = 18;
const W = 210 - M * 2;

export function generateFinalReportPdf({
  profile, internship, reportTitle, chapters = [], draft = {},
  snapshots = [], evaluations = [], template = null, layout = null, verification = null,
}) {
  const L = { ...LAYOUT_DEFAULTS, ...(layout ?? {}) };
  const title = reportTitle || 'Final Training Report';
  const accent = L.accent;
  const compact = L.density === 'compact';
  const fs = (n) => (compact ? Math.max(6, n - 1) : n);

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = M;

  if (L.show_cover) {
    doc.setFillColor(accent[0], accent[1], accent[2]);
    doc.rect(0, 0, 210, 70, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(fs(22));
    doc.setFont('helvetica', 'bold');
    doc.text(title, M, 34);
    doc.setFontSize(fs(12));
    doc.setFont('helvetica', 'normal');
    doc.text(profile?.full_name || 'Intern', M, 46);
    doc.setFontSize(fs(9));
    doc.setTextColor(210, 215, 225);
    doc.text('Generated by AIntern - logbook evidence supervisor-approved and digitally signed', M, 56);
    y = 86;
  }

  doc.setTextColor(30, 41, 59);
  const info = [
    ['Intern', profile?.full_name || '-'],
    ['University / Institution', profile?.university || '-'],
    ['Course / Programme', profile?.course || '-'],
    ['Host company', internship?.company_name || '-'],
    ['Department', internship?.department || '-'],
    ['Supervisor', `${internship?.supervisor_name || '-'} (${internship?.supervisor_email || ''})`],
    ['Internship period', `${internship?.start_date} to ${internship?.end_date}`],
    ['Report chapters', String(chapters.length)],
    ['Report generated', new Date().toISOString().split('T')[0]],
  ];
  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    theme: 'plain',
    styles: { fontSize: fs(10), cellPadding: compact ? 1.2 : 1.6 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 58 } },
    body: info,
  });

  chapters.forEach((ch) => {
    doc.addPage();
    y = M;

    if (ch.kind === 'auto_entries') {
      drawEntriesSection(doc, { snapshots, template, layout: L, accent, fs, M, W }, y);
      return;
    }
    if (ch.kind === 'auto_evaluations') {
      drawEvaluationsSection(doc, { evaluations, layout: L, accent, fs, M, W }, y);
      return;
    }

    // narrative — the student's own written text (or a placeholder)
    doc.setFontSize(fs(15));
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(accent[0], accent[1], accent[2]);
    doc.text(ch.chapter_title, M, y);
    y += 9;

    const text = String(draft?.[ch.chapter_id] ?? '').trim();
    const body = text || '(Not yet written.)';
    doc.setFontSize(fs(10));
    doc.setFont('helvetica', text ? 'normal' : 'italic');
    doc.setTextColor(text ? 51 : 148, text ? 65 : 163, text ? 85 : 184);
    body.split(/\n+/).forEach((para) => {
      doc.splitTextToSize(para, W).forEach((line) => {
        y = ensureSpace(doc, y, 6, M);
        doc.text(line, M, y);
        y += 5.2;
      });
      y += 3;
    });
  });

  drawVerificationAppendix(doc, { verification, accent, fs, M, W });

  const pages = doc.getNumberOfPages();
  const footer = L.footer_text || `${profile?.full_name || 'Intern'} - ${title}`;
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(fs(8));
    doc.setTextColor(148, 163, 184);
    doc.text(`${footer} | Page ${i} of ${pages}`, 105, 292, { align: 'center' });
  }

  const name = (profile?.full_name || 'intern').replace(/\s+/g, '_');
  doc.save(`AIntern_FinalReport_${name}_${internship?.start_date}_${internship?.end_date}.pdf`);
}

export default generateFinalReportPdf;
