/**
 * AIntern - Logbook PDF Generator (v1.1 R2 — layout-aware)
 *
 * Renders the SAME report model as the HTML preview, honoring the
 * resolved layout (spec 14-18): accent colour, title, section toggles,
 * density, footer. Presentation is configuration, not code.
 *
 * @file src/services/pdf/logbookPdf.js
 * @created July 10, 2026 - Session 10
 * @updated July 11, 2026 - v1.1 R2: layout configuration support
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { LAYOUT_DEFAULTS } from '../render/reportLayout';
import { qrPngDataUrl } from '../render/qr';

const M = 18;
const W = 210 - M * 2;

const RUBRIC_LABELS = {
  communication: 'Communication',
  punctuality: 'Punctuality & discipline',
  problem_solving: 'Problem-solving',
  quality: 'Quality of work',
  initiative: 'Initiative',
  teamwork: 'Teamwork',
  professionalism: 'Professionalism',
};

function ensureSpace(doc, y, needed) {
  if (y + needed > 282) {
    doc.addPage();
    return M;
  }
  return y;
}

function fieldRows(data, template) {
  const rows = [];
  (template?.fields_schema?.sections ?? []).forEach((section) => {
    (section.fields ?? []).forEach((f) => {
      const v = data?.[`${section.section_id}.${f.field_id}`];
      if (v !== undefined && v !== null && String(v).trim() !== '') {
        rows.push([f.field_name, String(v)]);
      }
    });
  });
  return rows;
}

export function generateLogbookPdf({ profile, internship, snapshots, evaluations, template, layout = null, verification = null }) {
  const L = { ...LAYOUT_DEFAULTS, ...(layout ?? {}) };
  const accent = L.accent;
  const compact = L.density === 'compact';
  const fs = (n) => (compact ? Math.max(6, n - 1) : n);
  const evals = L.show_evaluations ? evaluations : [];

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = M;

  if (L.show_cover) {
    doc.setFillColor(accent[0], accent[1], accent[2]);
    doc.rect(0, 0, 210, 70, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(fs(26));
    doc.setFont('helvetica', 'bold');
    doc.text(L.title, M, 34);
    doc.setFontSize(fs(12));
    doc.setFont('helvetica', 'normal');
    doc.text(profile?.full_name || 'Intern', M, 46);
    doc.setFontSize(fs(9));
    doc.setTextColor(210, 215, 225);
    doc.text('Generated by AIntern - every entry supervisor-approved and digitally signed', M, 56);
    y = 86;
  }

  doc.setTextColor(30, 41, 59);
  const info = [
    ['Intern', profile?.full_name || '-'],
    ['University / Institution', profile?.university || '-'],
    ['Course / Programme', profile?.course || '-'],
    ['Host company', internship?.company_name || '-'],
    ['Department', internship?.department || '-'],
    ['Supervisor', `${internship?.supervisor_name || '-'} (${internship?.supervisor_email || ''})`],
    ['Internship period', `${internship?.start_date} to ${internship?.end_date}`],
    ['Approved daily entries', String(snapshots.length)],
    ['Supervisor evaluations', String(evaluations.length)],
    ['Report generated', new Date().toISOString().split('T')[0]],
  ];
  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    theme: 'plain',
    styles: { fontSize: fs(10), cellPadding: compact ? 1.2 : 1.6 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 58 } },
    body: info,
  });

  doc.addPage();
  y = M;
  doc.setFontSize(fs(16));
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(accent[0], accent[1], accent[2]);
  doc.text('Approved Daily Entries', M, y);
  y += 8;

  snapshots.forEach((snap) => {
    y = ensureSpace(doc, y, 40);

    doc.setFillColor(241, 245, 249);
    doc.rect(M, y, W, 8, 'F');
    doc.setFontSize(fs(11));
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(accent[0], accent[1], accent[2]);
    doc.text(snap.entry_date, M + 2, y + 5.5);
    doc.setFontSize(fs(8));
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Approved ${String(snap.approved_at).slice(0, 10)}`, M + W - 2, y + 5.5, { align: 'right' });
    y += 10;

    autoTable(doc, {
      startY: y,
      margin: { left: M, right: M },
      theme: 'grid',
      styles: { fontSize: fs(9), cellPadding: compact ? 1.2 : 1.6, lineColor: [226, 232, 240], textColor: [30, 41, 59] },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 48, fillColor: [248, 250, 252] } },
      body: fieldRows(snap.content, template),
    });
    y = doc.lastAutoTable.finalY + 3;

    if (L.show_comments && snap.supervisor_comment) {
      y = ensureSpace(doc, y, 12);
      doc.setFontSize(fs(9));
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(71, 85, 105);
      const comment = doc.splitTextToSize(`Supervisor: ${snap.supervisor_comment}`, W);
      doc.text(comment, M, y + 4);
      y += comment.length * 4 + 3;
    }

    if (L.show_signatures && snap.supervisor_signature?.startsWith('data:image')) {
      y = ensureSpace(doc, y, 22);
      try {
        doc.addImage(snap.supervisor_signature, 'PNG', M, y, 36, 12);
        doc.setFontSize(fs(7));
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(148, 163, 184);
        doc.text(`Signed by ${snap.supervisor_name}`, M, y + 15);
        y += 18;
      } catch { /* skip malformed signature image */ }
    }
    y += 4;
  });

  if (evals.length > 0) {
    doc.addPage();
    y = M;
    doc.setFontSize(fs(16));
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(accent[0], accent[1], accent[2]);
    doc.text('Supervisor Evaluations', M, y);
    y += 8;

    evals.forEach((ev) => {
      y = ensureSpace(doc, y, 60);
      doc.setFontSize(fs(11));
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(30, 41, 59);
      doc.text(`${ev.period_start} to ${ev.period_end} (${ev.cadence_days}-day review)`, M, y + 4);
      y += 7;

      doc.setFontSize(fs(8));
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      const s = ev.summary ?? {};
      doc.text(
        `Days logged: ${s.days_logged ?? '-'} | Approved entries: ${s.approved_count ?? '-'} | Total hours: ${s.total_hours ?? '-'}`,
        M, y + 3,
      );
      y += 6;

      const scoreRows = Object.entries(RUBRIC_LABELS)
        .filter(([k]) => ev.scores?.[k])
        .map(([k, label]) => [label, `${ev.scores[k]} / 5`]);
      (ev.custom_kpis ?? []).forEach((kpi) => {
        if (kpi?.name && kpi?.score) scoreRows.push([`${kpi.name} (custom)`, `${kpi.score} / 5`]);
      });

      autoTable(doc, {
        startY: y,
        margin: { left: M, right: M },
        theme: 'grid',
        styles: { fontSize: fs(9), cellPadding: compact ? 1.2 : 1.6, lineColor: [226, 232, 240], textColor: [30, 41, 59] },
        columnStyles: { 0: { cellWidth: 100 }, 1: { halign: 'center' } },
        head: [['Criterion', 'Rating']],
        headStyles: { fillColor: accent, fontSize: fs(9) },
        body: scoreRows,
      });
      y = doc.lastAutoTable.finalY + 4;

      const comments = [
        ['Strengths', ev.comments?.strengths],
        ['Areas for improvement', ev.comments?.improvements],
      ].filter(([, v]) => v && String(v).trim());
      comments.forEach(([label, text]) => {
        y = ensureSpace(doc, y, 14);
        doc.setFontSize(fs(9));
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 41, 59);
        doc.text(label, M, y + 4);
        doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(String(text), W);
        doc.text(lines, M, y + 9);
        y += 9 + lines.length * 4;
      });

      if (L.show_signatures && ev.supervisor_signature?.startsWith('data:image')) {
        y = ensureSpace(doc, y, 22);
        try {
          doc.addImage(ev.supervisor_signature, 'PNG', M, y, 36, 12);
          doc.setFontSize(fs(7));
          doc.setTextColor(148, 163, 184);
          doc.text(`Signed by ${ev.supervisor_name} | ${String(ev.submitted_at).slice(0, 10)}`, M, y + 15);
          y += 18;
        } catch { /* skip */ }
      }
      y += 6;
    });
  }

  // ── Verification Appendix (v1.1 R3, spec 25-27) — verified only ─────
  if (verification?.verification_id) {
    doc.addPage();
    y = M;
    doc.setFontSize(fs(16));
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(accent[0], accent[1], accent[2]);
    doc.text('Verification Appendix', M, y);
    y += 8;

    autoTable(doc, {
      startY: y,
      margin: { left: M, right: M },
      theme: 'grid',
      styles: { fontSize: fs(9), cellPadding: 1.8, lineColor: [226, 232, 240], textColor: [30, 41, 59] },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 55, fillColor: [248, 250, 252] } },
      body: [
        ['Verification status', 'VERIFIED'],
        ['Verification ID', verification.verification_id],
        ['Report version', `v${verification.version}`],
        ['Snapshot created', String(verification.created_at).slice(0, 10)],
        ['Record fingerprint', String(verification.content_hash)],
        ['Verify online', verification.verify_url],
      ],
    });
    y = doc.lastAutoTable.finalY + 8;

    const qrUrl = qrPngDataUrl(verification.verify_url);
    if (qrUrl) {
      try {
        doc.addImage(qrUrl, 'PNG', M, y, 34, 34);
      } catch { /* QR optional */ }
    }
    doc.setFontSize(fs(9));
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(71, 85, 105);
    const note = doc.splitTextToSize(
      'Scan the QR code or visit the link above to confirm this document was '
      + 'generated from an officially verified internship record. Every entry was '
      + 'individually approved and digitally signed by the workplace supervisor. '
      + 'This appendix verifies authenticity without exposing report content.',
      W - 42,
    );
    doc.text(note, M + 40, y + 5);
  }

  const pages = doc.getNumberOfPages();
  const footer = L.footer_text || `${profile?.full_name || 'Intern'} - ${L.title}`;
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(fs(8));
    doc.setTextColor(148, 163, 184);
    doc.text(`${footer} | Page ${i} of ${pages}`, 105, 292, { align: 'center' });
  }

  const name = (profile?.full_name || 'intern').replace(/\s+/g, '_');
  doc.save(`AIntern_Logbook_${name}_${internship?.start_date}_${internship?.end_date}.pdf`);
}

export default generateLogbookPdf;
