/**
 * AIntern - Logbook PDF Generator (Phase 3, Session 10)
 *
 * Builds the default internship logbook PDF from the authoritative
 * record (approved snapshots + evaluations) entirely client-side with
 * jsPDF — zero cost, works offline once data is loaded.
 *
 * AI-imported university formats (Template Studio) layer on top in S11;
 * this is the clean default every intern gets.
 *
 * @file src/services/pdf/logbookPdf.js
 * @created July 10, 2026 - Session 10
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const M = 18;          // page margin (mm)
const W = 210 - M * 2; // usable width (A4 portrait)

const RUBRIC_LABELS = {
  communication: 'Communication',
  punctuality: 'Punctuality & discipline',
  problem_solving: 'Problem-solving',
  quality: 'Quality of work',
  initiative: 'Initiative',
  teamwork: 'Teamwork',
  professionalism: 'Professionalism',
};

function ensureSpace(doc, y, needed) {
  if (y + needed > 282) {
    doc.addPage();
    return M;
  }
  return y;
}

function fieldRows(data, template) {
  const rows = [];
  (template?.fields_schema?.sections ?? []).forEach((section) => {
    (section.fields ?? []).forEach((f) => {
      const v = data?.[`${section.section_id}.${f.field_id}`];
      if (v !== undefined && v !== null && String(v).trim() !== '') {
        rows.push([f.field_name, String(v)]);
      }
    });
  });
  return rows;
}

/**
 * Generate and save the logbook PDF.
 * @param {Object} p - { profile, internship, snapshots, evaluations, template }
 */
export function generateLogbookPdf({ profile, internship, snapshots, evaluations, template }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });

  // ── Cover ────────────────────────────────────────────────────────────
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, 210, 70, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(26);
  doc.setFont('helvetica', 'bold');
  doc.text('Internship Logbook', M, 34);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(profile?.full_name || 'Intern', M, 46);
  doc.setFontSize(9);
  doc.setTextColor(180, 190, 205);
  doc.text('Generated by AIntern — every entry supervisor-approved and digitally signed', M, 56);

  doc.setTextColor(30, 41, 59);
  let y = 86;
  const info = [
    ['Intern', profile?.full_name || '—'],
    ['University / Institution', profile?.university || '—'],
    ['Course / Programme', profile?.course || '—'],
    ['Host company', internship?.company_name || '—'],
    ['Department', internship?.department || '—'],
    ['Supervisor', `${internship?.supervisor_name || '—'} (${internship?.supervisor_email || ''})`],
    ['Internship period', `${internship?.start_date} to ${internship?.end_date}`],
    ['Approved daily entries', String(snapshots.length)],
    ['Supervisor evaluations', String(evaluations.length)],
    ['Logbook generated', new Date().toISOString().split('T')[0]],
  ];
  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    theme: 'plain',
    styles: { fontSize: 10, cellPadding: 1.6 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 58 } },
    body: info,
  });

  // ── Daily entries ────────────────────────────────────────────────────
  doc.addPage();
  y = M;
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Approved Daily Entries', M, y);
  y += 8;

  snapshots.forEach((snap) => {
    y = ensureSpace(doc, y, 40);

    // Date bar
    doc.setFillColor(241, 245, 249);
    doc.rect(M, y, W, 8, 'F');
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text(snap.entry_date, M + 2, y + 5.5);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 116, 139);
    doc.text(`Approved ${String(snap.approved_at).slice(0, 10)}`, M + W - 2, y + 5.5, { align: 'right' });
    y += 10;

    autoTable(doc, {
      startY: y,
      margin: { left: M, right: M },
      theme: 'grid',
      styles: { fontSize: 9, cellPadding: 1.6, lineColor: [226, 232, 240], textColor: [30, 41, 59] },
      columnStyles: { 0: { fontStyle: 'bold', cellWidth: 48, fillColor: [248, 250, 252] } },
      body: fieldRows(snap.content, template),
    });
    y = doc.lastAutoTable.finalY + 3;

    if (snap.supervisor_comment) {
      y = ensureSpace(doc, y, 12);
      doc.setFontSize(9);
      doc.setFont('helvetica', 'italic');
      doc.setTextColor(71, 85, 105);
      const comment = doc.splitTextToSize(`Supervisor: ${snap.supervisor_comment}`, W);
      doc.text(comment, M, y + 4);
      y += comment.length * 4 + 3;
    }

    if (snap.supervisor_signature?.startsWith('data:image')) {
      y = ensureSpace(doc, y, 22);
      try {
        doc.addImage(snap.supervisor_signature, 'PNG', M, y, 36, 12);
        doc.setFontSize(7);
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(148, 163, 184);
        doc.text(`Signed by ${snap.supervisor_name}`, M, y + 15);
        y += 18;
      } catch { /* skip malformed signature image */ }
    }
    y += 4;
  });

  // ── Evaluations ──────────────────────────────────────────────────────
  if (evaluations.length > 0) {
    doc.addPage();
    y = M;
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(15, 23, 42);
    doc.text('Supervisor Evaluations', M, y);
    y += 8;

    evaluations.forEach((ev) => {
      y = ensureSpace(doc, y, 60);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`${ev.period_start} to ${ev.period_end} (${ev.cadence_days}-day review)`, M, y + 4);
      y += 7;

      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 116, 139);
      const s = ev.summary ?? {};
      doc.text(
        `Days logged: ${s.days_logged ?? '—'} · Approved entries: ${s.approved_count ?? '—'} · Total hours: ${s.total_hours ?? '—'}`,
        M, y + 3,
      );
      y += 6;

      const scoreRows = Object.entries(RUBRIC_LABELS)
        .filter(([k]) => ev.scores?.[k])
        .map(([k, label]) => [label, `${ev.scores[k]} / 5`]);
      (ev.custom_kpis ?? []).forEach((kpi) => {
        if (kpi?.name && kpi?.score) scoreRows.push([`${kpi.name} (custom)`, `${kpi.score} / 5`]);
      });

      autoTable(doc, {
        startY: y,
        margin: { left: M, right: M },
        theme: 'grid',
        styles: { fontSize: 9, cellPadding: 1.6, lineColor: [226, 232, 240], textColor: [30, 41, 59] },
        columnStyles: { 0: { cellWidth: 100 }, 1: { halign: 'center' } },
        head: [['Criterion', 'Rating']],
        headStyles: { fillColor: [15, 23, 42], fontSize: 9 },
        body: scoreRows,
      });
      y = doc.lastAutoTable.finalY + 4;

      const comments = [
        ['Strengths', ev.comments?.strengths],
        ['Areas for improvement', ev.comments?.improvements],
      ].filter(([, v]) => v && String(v).trim());
      comments.forEach(([label, text]) => {
        y = ensureSpace(doc, y, 14);
        doc.setFontSize(9);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(30, 41, 59);
        doc.text(label, M, y + 4);
        doc.setFont('helvetica', 'normal');
        const lines = doc.splitTextToSize(String(text), W);
        doc.text(lines, M, y + 9);
        y += 9 + lines.length * 4;
      });

      if (ev.supervisor_signature?.startsWith('data:image')) {
        y = ensureSpace(doc, y, 22);
        try {
          doc.addImage(ev.supervisor_signature, 'PNG', M, y, 36, 12);
          doc.setFontSize(7);
          doc.setTextColor(148, 163, 184);
          doc.text(`Signed by ${ev.supervisor_name} · ${String(ev.submitted_at).slice(0, 10)}`, M, y + 15);
          y += 18;
        } catch { /* skip */ }
      }
      y += 6;
    });
  }

  // ── Footer page numbers ──────────────────────────────────────────────
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`${profile?.full_name || 'Intern'} — Internship Logbook · Page ${i} of ${pages}`, 105, 292, { align: 'center' });
  }

  const name = (profile?.full_name || 'intern').replace(/\s+/g, '_');
  doc.save(`AIntern_Logbook_${name}_${internship?.start_date}_${internship?.end_date}.pdf`);
}

export default generateLogbookPdf;
