/**
 * AIntern - Logbook PDF Generator (v1.1 R2 — layout-aware)
 *
 * Renders the SAME report model as the HTML preview, honoring the
 * resolved layout (spec 14-18): accent colour, title, section toggles,
 * density, footer. Presentation is configuration, not code.
 *
 * @file src/services/pdf/logbookPdf.js
 * @created July 10, 2026 - Session 10
 * @updated July 11, 2026 - v1.1 R2: layout configuration support
 * @updated July 12, 2026 - Phase B: entries/evaluations/verification-appendix
 *   drawing extracted to reportSections.js (shared with finalReportPdf.js) —
 *   behavior unchanged, just no longer duplicated.
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { LAYOUT_DEFAULTS } from '../render/reportLayout';
import { drawEntriesSection, drawEvaluationsSection, drawVerificationAppendix } from './reportSections';

const M = 18;
const W = 210 - M * 2;

export function generateLogbookPdf({ profile, internship, snapshots, evaluations, template, layout = null, verification = null }) {
  const L = { ...LAYOUT_DEFAULTS, ...(layout ?? {}) };
  const accent = L.accent;
  const compact = L.density === 'compact';
  const fs = (n) => (compact ? Math.max(6, n - 1) : n);
  const evals = L.show_evaluations ? evaluations : [];

  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  let y = M;

  if (L.show_cover) {
    doc.setFillColor(accent[0], accent[1], accent[2]);
    doc.rect(0, 0, 210, 70, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(fs(26));
    doc.setFont('helvetica', 'bold');
    doc.text(L.title, M, 34);
    doc.setFontSize(fs(12));
    doc.setFont('helvetica', 'normal');
    doc.text(profile?.full_name || 'Intern', M, 46);
    doc.setFontSize(fs(9));
    doc.setTextColor(210, 215, 225);
    doc.text('Generated by AIntern - every entry supervisor-approved and digitally signed', M, 56);
    y = 86;
  }

  doc.setTextColor(30, 41, 59);
  const info = [
    ['Intern', profile?.full_name || '-'],
    ['University / Institution', profile?.university || '-'],
    ['Course / Programme', profile?.course || '-'],
    ['Host company', internship?.company_name || '-'],
    ['Department', internship?.department || '-'],
    ['Supervisor', `${internship?.supervisor_name || '-'} (${internship?.supervisor_email || ''})`],
    ['Internship period', `${internship?.start_date} to ${internship?.end_date}`],
    ['Approved daily entries', String(snapshots.length)],
    ['Supervisor evaluations', String(evaluations.length)],
    ['Report generated', new Date().toISOString().split('T')[0]],
  ];
  autoTable(doc, {
    startY: y,
    margin: { left: M, right: M },
    theme: 'plain',
    styles: { fontSize: fs(10), cellPadding: compact ? 1.2 : 1.6 },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 58 } },
    body: info,
  });

  doc.addPage();
  y = drawEntriesSection(doc, { snapshots, template, layout: L, accent, fs, M, W }, M);

  if (evals.length > 0) {
    doc.addPage();
    y = drawEvaluationsSection(doc, { evaluations: evals, layout: L, accent, fs, M, W }, M);
  }

  drawVerificationAppendix(doc, { verification, accent, fs, M, W });

  const pages = doc.getNumberOfPages();
  const footer = L.footer_text || `${profile?.full_name || 'Intern'} - ${L.title}`;
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFontSize(fs(8));
    doc.setTextColor(148, 163, 184);
    doc.text(`${footer} | Page ${i} of ${pages}`, 105, 292, { align: 'center' });
  }

  const name = (profile?.full_name || 'intern').replace(/\s+/g, '_');
  doc.save(`AIntern_Logbook_${name}_${internship?.start_date}_${internship?.end_date}.pdf`);
}

export default generateLogbookPdf;
