/**
 * AIntern - Report Preview (v1.1 R2 — HTML live preview, spec §29)
 *
 * Full-screen HTML rendering of a report model + resolved layout.
 * Serves BOTH the working report (live records) and frozen official
 * versions — the caller supplies the model; this component only presents.
 *
 * @file src/components/report/ReportPreview.jsx
 * @created July 11, 2026 - v1.1 R2
 */

import { accentCss } from '../../services/render/reportLayout';
import { fieldRows as buildFieldRows } from '../../services/render/fieldRows';
import { XMarkIcon } from '@heroicons/react/24/outline';

const RUBRIC_LABELS = {
  communication: 'Communication',
  punctuality: 'Punctuality & discipline',
  problem_solving: 'Problem-solving',
  quality: 'Quality of work',
  initiative: 'Initiative',
  teamwork: 'Teamwork',
  professionalism: 'Professionalism',
};

function fieldRows(data, template) {
  return buildFieldRows(data, template).map((r) => ({
    label: r.field_name,
    lines: r.lines,
    section: r.section_name,
  }));
}

export default function ReportPreview({ model, layout, label = 'Preview', onClose }) {
  const accent = accentCss(layout.accent);
  const compact = layout.density === 'compact';
  const entries = model.entries ?? [];
  const evaluations = layout.show_evaluations ? (model.evaluations ?? []) : [];

  return (
    <div className="fixed inset-0 z-50 bg-gray-100 overflow-y-auto">
      {/* Toolbar */}
      <div className="sticky top-0 z-10 bg-slate-900 text-white px-4 py-3 flex items-center justify-between">
        <span className="text-sm font-medium">👁 {label} — HTML preview</span>
        <button onClick={onClose} aria-label="Close preview" className="p-1.5 rounded-md hover:bg-slate-700">
          <XMarkIcon className="w-5 h-5" />
        </button>
      </div>

      <div className={`max-w-2xl mx-auto bg-white shadow my-4 ${compact ? 'text-sm' : ''}`}>
        {/* Cover */}
        {layout.show_cover && (
          <div className="p-8 text-white" style={{ backgroundColor: accent }}>
            <h1 className={`font-bold ${compact ? 'text-2xl' : 'text-3xl'}`}>{layout.title}</h1>
            <p className="mt-2 text-lg opacity-90">{model.intern?.full_name || 'Intern'}</p>
            <p className="mt-1 text-xs opacity-70">
              Generated by AIntern — every entry supervisor-approved and digitally signed
            </p>
          </div>
        )}

        {/* Info */}
        <div className="p-6 border-b border-gray-200">
          <table className="w-full text-sm">
            <tbody>
              {[
                ['Intern', model.intern?.full_name],
                ['University / Institution', model.intern?.university],
                ['Course / Programme', model.intern?.course],
                ['Host company', model.internship?.company_name],
                ['Department', model.internship?.department],
                ['Supervisor', model.internship?.supervisor_name],
                ['Internship period', `${model.internship?.start_date} to ${model.internship?.end_date}`],
                ['Approved daily entries', String(entries.length)],
                ['Supervisor evaluations', String((model.evaluations ?? []).length)],
              ].filter(([, v]) => v && v !== 'undefined to undefined').map(([k, v]) => (
                <tr key={k}>
                  <td className="py-1 pr-4 font-semibold text-gray-700 w-48 align-top">{k}</td>
                  <td className="py-1 text-gray-800">{v}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Entries */}
        <div className="p-6 space-y-5">
          <h2 className="font-bold text-lg" style={{ color: accent }}>Approved Daily Entries</h2>
          {entries.length === 0 && <p className="text-sm text-gray-400">No approved entries in this report.</p>}
          {entries.map((e) => {
            const rows = fieldRows(e.content, model.template);
            let lastSection = null;
            return (
              <div key={e.entry_date + (e.snapshot_id ?? '')} className="border border-gray-200 rounded">
                <div className="px-3 py-1.5 flex justify-between items-center text-white text-sm font-semibold" style={{ backgroundColor: accent }}>
                  <span>{e.entry_date}</span>
                  <span className="text-xs font-normal opacity-80">Approved {String(e.approved_at).slice(0, 10)}</span>
                </div>
                <div className="p-3 space-y-1">
                  {rows.map((r, i) => {
                    const showSection = r.section !== lastSection;
                    lastSection = r.section;
                    return (
                      <div key={i}>
                        {showSection && (
                          <p className="text-[10px] font-bold uppercase tracking-wide text-gray-400 mt-2">{r.section}</p>
                        )}
                        {r.lines.length > 1 ? (
                          <div className="text-sm text-gray-800">
                            <span className="text-gray-500">{r.label}:</span>
                            <ul className="list-disc list-inside ml-1 mt-0.5">
                              {r.lines.map((line, li) => <li key={li}>{line}</li>)}
                            </ul>
                          </div>
                        ) : (
                          <p className="text-sm text-gray-800">
                            <span className="text-gray-500">{r.label}:</span> {r.lines[0]}
                          </p>
                        )}
                      </div>
                    );
                  })}
                  {layout.show_comments && e.supervisor_comment && (
                    <p className="text-sm italic text-gray-600 pt-1">
                      Supervisor: {e.supervisor_comment}
                    </p>
                  )}
                  {layout.show_signatures && e.supervisor_signature?.startsWith('data:image') && (
                    <div className="pt-1">
                      <img src={e.supervisor_signature} alt="Supervisor signature" className="h-10" />
                      <p className="text-[10px] text-gray-400">Signed by {e.supervisor_name}</p>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>

        {/* Evaluations */}
        {evaluations.length > 0 && (
          <div className="p-6 space-y-5 border-t border-gray-200">
            <h2 className="font-bold text-lg" style={{ color: accent }}>Supervisor Evaluations</h2>
            {evaluations.map((ev, idx) => (
              <div key={ev.evaluation_id ?? idx} className="border border-gray-200 rounded p-3 space-y-2">
                <p className="font-semibold text-sm text-gray-900">
                  {ev.period_start} to {ev.period_end} ({ev.cadence_days}-day review)
                </p>
                <p className="text-xs text-gray-500">
                  Days logged: {ev.summary?.days_logged ?? '—'} · Approved: {ev.summary?.approved_count ?? '—'} · Hours: {ev.summary?.total_hours ?? '—'}
                </p>
                <table className="w-full text-sm">
                  <tbody>
                    {Object.entries(RUBRIC_LABELS).filter(([k]) => ev.scores?.[k]).map(([k, lbl]) => (
                      <tr key={k} className="border-b border-gray-100">
                        <td className="py-0.5 text-gray-700">{lbl}</td>
                        <td className="py-0.5 text-right font-semibold text-gray-900">{ev.scores[k]} / 5</td>
                      </tr>
                    ))}
                    {(ev.custom_kpis ?? []).filter((k) => k?.name && k?.score).map((k) => (
                      <tr key={k.name} className="border-b border-gray-100">
                        <td className="py-0.5 text-gray-700">{k.name} <span className="text-gray-400">(custom)</span></td>
                        <td className="py-0.5 text-right font-semibold text-gray-900">{k.score} / 5</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                {ev.comments?.strengths && (
                  <p className="text-sm text-gray-700"><span className="font-semibold">Strengths:</span> {ev.comments.strengths}</p>
                )}
                {ev.comments?.improvements && (
                  <p className="text-sm text-gray-700"><span className="font-semibold">Areas for improvement:</span> {ev.comments.improvements}</p>
                )}
                {layout.show_signatures && ev.supervisor_signature?.startsWith('data:image') && (
                  <div>
                    <img src={ev.supervisor_signature} alt="Supervisor signature" className="h-10" />
                    <p className="text-[10px] text-gray-400">
                      Signed by {ev.supervisor_name} · {String(ev.submitted_at).slice(0, 10)}
                    </p>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}

        {/* Footer */}
        <div className="px-6 py-4 text-center text-[11px] text-gray-400 border-t border-gray-200">
          {layout.footer_text || `${model.intern?.full_name || 'Intern'} — ${layout.title}`}
        </div>
      </div>
    </div>
  );
}
